### ISSUE TITLE
Multiple Middleware on Route Hangs

### ISSUE THREAD

**Issue by SupremeTechnopriest** [kartikk221/hyper-express#68]
Hey @kartikk221!

I rolled out my new micro services backed by `hyper-express` and our recent changes and I noticed a bug.  I'm trying to track it down, but I might need to tag you in as you are more familiar with this change.  

When you define middleware on a specific route, it seems like every other request hangs and eventually fails.  Here is a quick and easy reproduction.  We should add this to the tests.

```ts
import { 
  Server,
  type Request,
  type Response,
  type MiddlewareNext
} from 'hyper-express'

const app = new Server()

app.post(
  '/echo',
  async (req: Request, res: Response, next: MiddlewareNext) => {
    req.body = await req.json()
    next()
  },
 (req: Request, res: Response, next: MiddlewareNext) => {
    res.locals.data = req.body
    next()
  },
 (req: Request, res: Response) => {
    res.status(200).json(res.locals.data)
  }
)

app.listen(3000)
```

Then if you use Postman to `POST` to `localhost:3000/echo` with a request body:

```json
{ "foo": "bar" }
```

Every other request hangs.  Oddly this doesn't happen when you `curl` which leads me to believe that the socket isn't being closed on the server side. 

Any insight?

**Comment by SupremeTechnopriest** [comment]
Here is the example in JS for ease of copy/paste:

```js
import {  Server } from 'hyper-express'

const app = new Server()

app.post(
  '/echo',
  async (req, res, next) => {
    req.body = await req.json()
    next()
  },
  async (req, res, next) => {
    res.locals.data = req.body
    next()
  },
  async (req, res) => {
    res.status(200).json(res.locals.data)
  }
)

app.listen(3000)
```

**Comment by kartikk221** [comment]
@SupremeTechnopriest I can add this to tests but one thing I noticed with your code is that in the first middleware. You have an async middleware but you also call "next()". For async middlewares, you do not have to call next() as the Promise returned by the async function is awaited by HyperExpress.

**Comment by SupremeTechnopriest** [comment]
Sure let me give that a go.

**Comment by SupremeTechnopriest** [comment]
So when I remove the `next()` call  I get the following error:

```
HyperExpress: Double middleware execution detected! You have a bug where one of your middlewares is calling both the next() callback and also resolving from a Promise/async callback. You must only use one of these not both.
```

```ts
app.post(
    '/echo',
    async (req: Request, res: Response, next: MiddlewareNext) => {
      req.body = await req.json()
    },
    (req: Request, res: Response, next: MiddlewareNext) => {
      res.locals.data = req.body
      next()
    },
    (req: Request, res: Response) => {
      res.status(200).json(res.locals.data)
    }
  )```

With the `next()` call in the async, it returns the response once and then throws an `ECONNRESET`.  Maybe some logic is inverted?

**Comment by SupremeTechnopriest** [comment]
It's worth noting that even with the error throwing (next removed) the second request still hangs.

**Comment by SupremeTechnopriest** [comment]
Were you able to recreate it in the tests?

**Comment by kartikk221** [comment]
@SupremeTechnopriest I just added a test for this and pushed it. Can you clone/pull the latest commit and run the tests on your machine?

**Comment by SupremeTechnopriest** [comment]
let me give it a go.

**Comment by SupremeTechnopriest** [comment]
So I had another async middleware that was calling `next`. Pulled that out and I stopped getting the error, but the main issue is still persisting (the hanging on the second call).  I create a very minimal test file to make sure its not related to my code:

```js
const { Server } = require('hyper-express')

const app = new Server()

app.get('/', (_, res) => {
  res.status(200).send('Hello World')
})

app.post(
  '/echo',
  async (req) => {
    req.body = await req.json()
    return
  },
  (req, res, next) => {
    res.locals.data = req.body
    next()
  },
  (_, res) => {
    res.status(200).json(res.locals.data)
  }
)

app.listen(3000).then(() => {
  console.log('Listening')
})
```

The get method is throwing this error and crashing the server:

```
/node_modules/hyper-express/src/components/http/Request.js:93
        this.#raw_response.pause();
                           ^

Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at Request.pause (/Users/rl/Sites/projects/edgemesh/v4/core-api/node_modules/hyper-express/src/components/http/Request.js:93:28)
    at /Users/rl/Sites/projects/edgemesh/v4/core-api/node_modules/hyper-express/src/components/http/Request.js:160:46
```

The post method with the request body `{ "foo": "bar" }` echos back the body on the first call and then hangs on the second.  If I cancel the second call and submit a third, it returns.  Then it hangs... and so on. 

Could you run this file locally and test the routes with postman and confirm you get the same results?

**Comment by kartikk221** [comment]
So just to confirm you are testing these routes locally from Postman to trigger this error consistently on every other request?

**Comment by kartikk221** [comment]
Hey, was able to figure out the bug. It ended up being a weird behavior with Readable streams that I looked over when implementing them which was leading to some requests hanging due to the stream being in a paused state by default instead of flowing. This bug has been fixed in 6.0.3, so try upgrading to 6.0.3 to see If your bug still persists.

**Comment by SupremeTechnopriest** [comment]
Hey @kartikk221!

That definitely fixed the middleware issue, but the route without middleware is still throwing that Invalid Access error.  Yes I was testing with postman.

```js
const { Server } = require('hyper-express')

const app = new Server()

app.get('/', (_, res) => {
  res.status(200).send('Hello World')
})

app.listen(3000).then(() => {
  console.log('Listening')
})
```

#### `GET /` 
```
/node_modules/hyper-express/src/components/http/Request.js:95
            this.#raw_response.pause();
                               ^

Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at Request.pause (/Users/rl/Sites/projects/edgemesh/v4/core-api/node_modules/hyper-express/src/components/http/Request.js:95:32)
    at /Users/rl/Sites/projects/edgemesh/v4/core-api/node_modules/hyper-express/src/components/http/Request.js:183:46
```

**Comment by kartikk221** [comment]
> That definitely fixed the middleware issue, but the route without middleware is still throwing that Invalid Access error. Yes I was testing with postman.

I added tests for the code you provided in the above scenarios to the repository. Are you able to run all of the tests for HyperExpress normally in your environment?

**Comment by SupremeTechnopriest** [comment]
Im still having issues with that submodule.  Let me see if I can resolve it.

**Comment by kartikk221** [comment]
I also receive this error for some reason. For me on Windows, this is usually resolved by using Git Bash program.

**Comment by kartikk221** [comment]
Also, from the error trace you provided above, It seems like the error occurs here [Request.js](https://github.com/kartikk221/hyper-express/blob/eed6f68fcf839777914cc2e9730d59904f2884ef/src/components/http/Request.js#L183) which essentially means that there is still Request body data being received but the response has already been sent. This makes no sense to me because  uWebsockets.js will stop downloading any data If the response has been sent.

**Comment by SupremeTechnopriest** [comment]
Yeah this is definitely weird, because it wasn't happening before and just randomly started happening yesterday.

**Comment by kartikk221** [comment]
> I'm working on a mac at the moment which is also unix. I will try to fix it, in the mean time can you run that script locally and hit it with postman?

Runs fine on my end [GIF](https://gyazo.com/9c92fdd3c60a2ad2029b4dd5665db652) but there is an additional boolean check I can add in the body streamer to potentially prevent your problem based on the error trace.

**Comment by SupremeTechnopriest** [comment]
So weird.... I wonder why we are getting different results.

**Comment by kartikk221** [comment]
> So weird.... I wonder why we are getting different results.

I just pushed a commit with stricter checks on the Request's body stream. Try pulling the new commit and testing to see If those checks fix your situation.

Also, are you making the Postman request to HyperExpress serving requests from a remote machine or from your mac itself?

**Comment by SupremeTechnopriest** [comment]
Did you publish it to npm or should pull upstream and link? Also I manually cloned the submodule and tests all pass.

**Comment by kartikk221** [comment]
> Did you publish it to npm or should pull upstream and link? Also I manually cloned the submodule and tests all pass.

Just pushed it to this respository not NPM, so you should be able to pull upstream and run the tests again along with your code.

**Comment by SupremeTechnopriest** [comment]
Still the same error.

**Comment by kartikk221** [comment]
> Still the same error.

So all of the tests pass but your GET endpoint that serves "Hello World" throws the discarded access error? Did anything about the error change in terms of the trace? Is it the exact same line that calls the Request.pause() method leading to the error?

**Comment by SupremeTechnopriest** [comment]
Okay I figured it out.  It happens when you send a body on a GET method.  I accidentally had the body from an old request in postman.  Maybe we should protect against this?

**Comment by SupremeTechnopriest** [comment]
Cool!  Let me try it out.

**Comment by SupremeTechnopriest** [comment]
Looks good to me!  Ship it!

**Comment by kartikk221** [comment]
Absolutely, this is something that I thought was already handled at the low-level with uWebsockets.js but I guess not and hence this was even a problem in the first place.

**Comment by SupremeTechnopriest** [comment]
We should definitely do that as well.  Im sure @alexhultman would appreciate it.
